### ISSUE TITLE
Christakis and Fowler Analysis

### ISSUE THREAD

**Issue by johanna-einsiedler** [osofr/Ogburn_etal_simulations#1]
Hi!

I have been reading your paper and in Section 4.6, where you are analysing the Framingham Heart Study this Github Repository is referred to for the source code. However, I was only able to find the simulation code (not the one used for analysing the obesity study). Would you be able to point me in the right direction (maybe I just overlooked it)?

Thanks a lot!

**Comment by osofr** [comment]
Hi, thanks for reaching out and apologies for the delay! Please see the attached code, I will also add it to the repo shortly.
[final analysis for paper.R.zip](https://github.com/osofr/Ogburn_etal_simulations/files/8476859/final.analysis.for.paper.R.zip)

**Comment by osofr** [comment]
Please also see [here](https://github.com/osofr/Ogburn_etal_simulations/tree/master/analysis)
